version: '3'

networks:
  backend:
    driver: bridge

services:

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - backend
    expose:
      - 2181
  
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://$KAFKA_INTERNET_HOST:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: $KAFKA_CREATE_TOPICS
      KAFKA_SECURITY_PROTOCOL: PLAINTEXT
    depends_on: 
      - zookeeper
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/certificates

        #manager:
        #image: sheepkiller/kafka-manager:stable
        #environment:
        #ZK_HOSTS: zookeeper:2181
        #APPLICATION_SECRET: LetMeIn
        #networks:
        #- backend
        #depends_on:
        #- zookeeper
        #ports:
        #- ${KAFKA_MANAGER_PORT}:9000
